import express from 'express';
import dotenv from 'dotenv';
import cors from 'cors';
import cookieParser from 'cookie-parser';
import path from 'path';
import authRoutes from './routes/authRoutes';
import mediaRoutes from './routes/mediaRoutes';
import { errorHandler } from './middleware/errorMiddleware';
dotenv.config();
const app = express();
const PORT = process.env.PORT || 5001;
app.use(cors({ origin: 'http://localhost:3000', credentials: true }));
app.use(express.json());
app.use(cookieParser());
app.use('/uploads', express.static(path.join(__dirname, '../uploads')));
app.use('/api/auth', authRoutes);
app.use('/api/media', mediaRoutes);
app.use(errorHandler);
app.listen(PORT, () => {
  console.log(`Backend server is running on http://localhost:${PORT}`);
});
